apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dddsddsfds
  janus-idp.io/tekton: dddsddsfds
  backstage.io/kubernetes-id: dddsddsfds
  backstage.io/kubernetes-namespace: openshift-gitops 
  app.kubernetes.io/part-of: dddsddsfds
resources: 
- deployment.yaml
- route.yaml
- service.yaml
